#!/usr/bin/env bash
# install nginx web server
# the server should be listening on port 80

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

# Configure your Nginx server so that /redirect_me is redirecting to another page.
redirect="server_name _;\\
location /redirect_me {\\
	return 301 https://www.youtube.com;\\
}"

sudo sed -i "s|server_name _;|$redirect|" /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
