#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP through the firewall
sudo ufw allow 'Nginx HTTP'

# Configure Nginx to redirect /redirect_me to https://www.youtube.com
str="server_name _;\\
	rewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s|server_name _;|$str|" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx start
sudo service nginx restart
