#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP through the firewall
sudo ufw allow 'Nginx Full'

# Configure Nginx to redirect /redirect_me to https://www.youtube.com

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

str="server_name _;\\
	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s|server_name _;|$str|" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
