#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP through the firewall
sudo ufw allow 'Nginx HTTP'

# Configure Nginx to redirect /redirect_me to https://www.youtube.com
str="server_name _;\\
	rewrite /redirect_me https://www.youtube.com permanent;"

sudo sed -i "s|server_name _;|$str|" /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to redirect /redirect_me to https://www.youtube.com
sudo sed -i "48i error_page 404 /custom_404.html" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
